language: node_js
os: linux
node_js:
- '9'
script: echo "Running jobs Install, Build & Test against $(node -v) ..."
jobs:
  include:
  - stage: Install
    script:
    - echo "Installing needed modules"
    - npm install
  - stage: Build
    script:
    - echo "Running build script ..."
    - npm run-script build
  - stage: Test
    script:
    - echo "Testing branch - $(branch) ..."
    - npm test
  - stage: Merge to master
    if: "(type = pull_request)"
    script:
    - echo "Running github auto merge process for:" $TRAVIS_COMMIT
    - bash ./merge_script.sh
env:
  global:
  - secure: FhatVZxX9I3dW8T7rtuQs3TRbaOw/kULq/h1ySAUuRiclptdvYn9Sj8QVdN6UoYCDn5EqCTomVbhIuY4idCgnbyaXOj6i+WyjM+Zx2zE3QLzOu4aoO9F6WwBAGiBpA6GDtStHLiKjLreNhEp8lVnuG1dFCV0gqmCnDn4iY1AY6rXkQ0RZYreKi0SDBZH9CX5VOfNU1QK0NRQ6VoLggLQeNlfBMORnW6QwUJiKUMb0cmqPVXLZbUlHswFHjtURl9moy+XHifTAktld1wgTdMpTj/FYkclpfQGY8pBOdv2bWMpkGImjnNKSabvpzfhn0XMRxCjh2iyQCMffXMNr9yoJFGZkqGisnM5/TdrGHgT3b5DbUj6/xAkkv6wQaYeZNGpQd9XbnFYi8cbY0KGE8PkngtN9fRuLi9Leow3PnB+bhwv9BFA2upv+E/tBWFDO/Qv+ptFIGwJbu6HHBXZMolp38IPGaVomYv8drR76q+y2/XUnxUUXAeqMlDnuK1kAwcCyG1/H4OMzrYoygyXjliwjLFw4XOjU/fZHQal2m15W7+EhMWXJYzFvA7Jz7sDj2xdLFXcQGe/k0thZ5vqH8gBVB8zVWSNpdwn8aixb667WdXVspNMygD8tbR/vcx5fQ6gkd+Y2NfeB8Z0pZI/FVMVCjgG8pkY6726nQVrV4/QfGg=
