language: node_js
os: linux
node_js:
  - "9"

script: echo "Running jobs install then tests against $(node -v) ..."

jobs:
  include:
    - stage: npm install
      script:
        - echo "Installing needed modules"
        - npm install
    - stage: npm build
      script:
        - echo "Running build script ..."
        - npm run-script build
    - stage: npm test
      script:
        - echo "Testing branch - $(branch) ..."
        - npm test


