language: node_js
os: linux
node_js:
- '9'
script: echo "Running jobs Install, Build & Test against $(node -v) ..."
jobs:
  include:
  - stage: Install
    script:
    - echo "Installing needed modules"
    - npm install
  - stage: Build
    script:
    - echo "Running build script ..."
    - npm run-script build
  - stage: Test
    script:
    - echo "Testing branch..." $TRAVIS_BRANCH $TRAVIS_PULL_REQUEST_BRANCH
    - npm test
  - stage: Merge to master
    if: "(type = pull_request)"
    script:
    - echo "Running github auto merge process for:" $TRAVIS_PULL_REQUEST_BRANCH
    - bash ./merge_script.sh
env:
  global:
  - secure: FggLGlp351uhdAs7FAcNw0twP42+BknVTXmIJ+3GxwzZGult5HJ1SpXkjlf5C/epU5bVYLHPGDbmcjWnIg0jqR0vjXRFJnOeP3b1v8c2jeaZIROuSFAbwrsOGQ2amqEDbA/qAm3CHpugp6f3tGXX+VQPqqO77uazALEcD6/hrOgVj4heZvz9nACqQ3NUx80aUKY1QMcxhQAqG1F+Wd+J20CVgAzpUfwds443anZIIlILk0lkLPG7N4DZhUjyV4hRX3IxP1DWRETSbWcdyyzpQAbmegvSs/cUCngXjRKuB4chG2ED80DSTZVRmrrsJjOtj7NvFYuAm85nGE957FPP7qZO8bFniPeq5+XGdbc47fTcn26yP3BI/SNmMD+yFu7+gaVrKnEbr2PZMAm9+zkQqJBg2QxRFT6e2PHc9qw4AC/pzNXRJnjot6/Jl4A6ndVB8kSQAXTWPzVfXEWEQMvcUUfAZGo4CXz9++UvO9J3MlEMtxTazH62HorP7iLGqsIHBEC3b+JCd5W8fsVpLG5a3IXdOz4sX3c1knkJw7tIUNQpanu7hkwr5XFkFSLHbAvt/UdZiDX01Eu2ie1JuKprdAJLVKlGNq32JNc2oIYintej/QAy6Eo5tUUzZqQz34nQipozuSaxqqeDkLHbiELmxRnCKisvQUGt5rblLy5r8Ck=
  - secure: VMcoAhThWubYgpn2ycQ8RXdnRIwCcjbxim8s1qc0YrWCwBBcWThdaqCJZ+lUDuI7W+Q8/feEfUWMB1qpXk/PUA5qSEtVXO3WLK7cBbraJEkB+9DQV7w+cslK3UtAhUJGH0KBXB2z2q5xt+Kvwcj4FqAlBRB7kpZYMKCWzRZ5SvtMkrk4dvoF6a04nIaSieOdBV8v4FOEu8bf4cXCGirnQQQQVBJ2YGojIJSp8GgMxXL9RcOBuGbjJ3E1cXzG+hgCaBVeTAlpFgByUhwFIVdRc6DKS7NBiqyWL0b0VJFbZyPshCw/4JJXiAs1hdCIAiHOPXzgEewsEfQEI3zhxL0pjaJsnbSjxeAUzhGWKsKKFRGdmrO/WhGe4v0behR5LBdb6fU/AMgvXyfCo/+ZIl0HhKVm+biL4wwwA87WoHeGqj5+OXsRobL8NaKln4I09bd9fvfcLriGDNCcaUm1bbGDGL+MESLw8kP13vnpdxNlfwnSZfHNcUBnxI3jlPfhaOmvkXgBafx/1PT7FeRbBM3BukcV2e+X2h7LHjHtqXsjhwq+/Mg1NO3tXD/d6+O8U/XzT5Dvw0XfGgbvILg6e84qOAShKZzMN6W0kwbZqNGowLMYV9D0QDwjqqsc+BFUVxJp72O7QeburS+YdYvZX0dYpWQNPV3K5xYrlj/pPqiBmjo=
  - secure: M/uTstDqRFS0/A3/rKbMxbL6YXcfD0L/Ky4y5eyBYAaehaage0gMJBKiFsQpORVOtbKaFVgbcezQG99ks8fCdcwcS94qsAIMNG9O6zeznfoI7yHtEmvo8810xYUKm+jXqSMgufAoAtFb9e/8JwV9voYozrWUfqkkVBn/Y9XMxXH++TwLG15znAsSWx6lLmHmLCkFOE93mTgziVZugMCD4xzPPpiwONSYS6KDMBG5uvRCmOWo1xEn5nGQ6sAcUhRiKb9cOo6YE+52kAH68zX8DdHGrEMtFgzPjTu+DsJbrDQaO+Fb8h3syvwVnCzgP/QuN3k+cEthlDXifamcISSr29BJ8CN8j5YcDwz6rNVNIMnRLHOAVEVjEoNRP3xDLKIJuhqJ2jc8UPYAMCw2M5ZgnwOm91iuZgscZRL/EQZL9bpJTdL5igg01fsPvvdJP6FAaP8jmfn6osRU5MgznuCjgTdUNQIYwe/biyfqmLWsNrvHrzvR7LErullyY553kCGkTbSXFXj6+OO8sKIAA/wUawh9UBGKwMHUtjr0q3eFKnEsvvzsLvICWg2Au2VMlvTz0R9FU0nM0JJAaCC0qcpTgCjUWfG3KcE0wJdtp/FMNWp9QAlph3A3wDgfRtU1PlEdXDB3FuZCWSv0pIH2MYxEYJCIVkpWPrEAwOxWh4IGGDY=
  - secure: E68dzZgv4zrZVV4sDeZ1fUEmauknzN63aiK/iKLiKaeJsSDLjB9YesxeZzoVwJ6tbBw2EG55I4WXw/td3pOXATD91Ro5wk2wItCoOssgPPn8n0EmOkAjs5FsNFUYo9Vx5sXaqsImG3vjQd2PFvJ8p38V4xRxqerUnaDGw4IcjMM8Ig65DrB0YE1kmpdhhdhsEB/vBOxPVUqxExZJKCR7alGOB0Pdt/Z4EcrOeJuT1KIliYxVxCb5aZNIszZUi/G+XFXnbN35roWuR4NXPOylCqwsyG1IqfPzY8QbU4hkj7I+ej7qTsn/8kV7DUta544mICkbng6m6RbT7GYcmc1oskJrbTmqL3EJkpWJtzDcKq/xVaPdImx6vPPujfUhr1ltO8wvFBZ4vNhJNUIs5eB8QSvOuMV6B8f4mqhlFnkgGrzkfVacDVZymgIUXgT1BJlfh/olm/vqI416ktRRILmLwrHHcQBWII6uGX135IkKDKo+hDhNxSDyOWgwrFXIv+HfTA+jthLncfyn4YRvZZcjHDpMIQIKBg6R8WtBaOV9jq9Yr9wlX8lCr3U6VGhwQbRnzc3F0vav+ztrl6r4eikU7FcDWN21ZbuD+vQV9/2iARoel7vtBtuuCiIieMxROSRkBwgzZ/2vHdhSZK17qW5BGxJfa+/SyZN3dxHdjsCI1Ck=
