language: node_js
os: linux
node_js:
- '9'
script: echo "Running jobs Install, Build & Test against $(node -v) ..."
env:
  global:
    - secure: WXZY8XSTFNo1eevwNxn7MzWPEvz9GKcIF25S3vnZc/ErbwFu712yR9fn4T4psn6HFzmfHHvwLBKvwsM3ozAkC1aFx/Zoj09JwTMX+EkH36KddaOw4cDkNu1swNgEgNV+wMWYjl/LGfcpMZFfDxB1LafnOHea/2tdhepYqQQmCHFcTJSAjVyOp854iiK0vJPZdIh1Jibkr8+bxlvkkdrKprlcPbXdluCoNps7T2Z7uwz9wsLwQJ5QLd6f0jLwvL4urxNae/w2fw39ZbhLFZ49xaGqvaGA189Z2IurvOd4h98AnPoBCPZ7TM1JG+1CBj4TWFqdJcQ9VuHK+xlHqcIh1ShXEVGQyaj0uSm2TWZCMSbrT6IlrSPVBYfe3DJ7wnPkH1HHCEjKVzuSvp6EUtXG6yp+XGzFQPElhJKpnwnuGCCf6kce+wnv42IsmuxTsJ1JjYbwMF82nFovoY0lJ6PRtHxnL2g1lHvror23aaw6hGmx2xa684LCtnWnCxJ/0b7FIn0wnPB/QXKfDB0nL9+xJcJZ6BuFWSZPMhvPgR9XItn428mWiLwEL4juFZ7EjrtLkcbJDg9eChaeV3n6mcv8iSsBMD0QB1vFnPnixEU7FEiYv0FsR6cWoBO9Zn081buwse/LRnQEJKoEzFiecjhJt3eHq1ozvazRvUNjB7HVwg8=
jobs:
  include:
    - stage: Install
    script:
    - echo "Installing needed modules"
    - npm install
    - stage: Build
    script:
    - echo "Running build script ..."
    - npm run-script build
    - stage: Test
    script:
    - echo "Testing branch - $(branch) ..."
    - npm test
    - stage: Merge to master
    if: "(type = pull_request)"
    script:
    - echo "Running github auto merge process ..."

    after_success: chmod +x ./merge_script.sh
